### ISSUE TITLE
Decide on Trello vs Github

### ISSUE THREAD

**Issue by brianking** [OSLC/awesome-oslc#2]
We've been having a conversation on email about this, let's move the conversation here.

**Comment by brianking** [comment]
As I said in an email, it's fine if we use both. The stuff I’m working on now (e.g. site rebuilding) is completely open so GH suits that. If Trello better suits your needs, please continue using it.

**Comment by berezovskyi** [comment]
I will abandon the Trello idea for the time being and try to adopt the GH project/issue approach.
